# Generated by Django 5.1.7 on 2025-03-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_device_level_device_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdevice',
            old_name='level',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='logsensor',
            old_name='level',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='level',
            new_name='value',
        ),
    ]
