# Generated by Django 5.1.7 on 2025-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_level_logdevice_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='threshold',
        ),
        migrations.AddField(
            model_name='plan',
            name='sign',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
