# Generated by Django 5.1.7 on 2025-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_sensor_sign_remove_sensor_threshold_plan_sign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsensor',
            name='on_off',
        ),
        migrations.AlterField(
            model_name='logdevice',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logsensor',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
