# Generated by Django 5.1.7 on 2025-04-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_device_value_alter_logdevice_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
