# Generated by Django 5.1.7 on 2025-04-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user_id',
            new_name='id',
        ),
    ]
