# Generated by Django 5.2 on 2025-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_plan_sign_remove_plan_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
