# Generated by Django 5.1.7 on 2025-05-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_plan_sign_remove_plan_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logdevice',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
