# Generated by Django 5.1.7 on 2025-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_device_value_alter_logdevice_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsensor',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
