# Generated by Django 5.1.7 on 2025-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_logsensor_value_alter_sensor_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='person',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
