# Generated by Django 5.2 on 2025-05-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_person_schedule_user_id_alter_schedule_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandevice',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
